on:
  push:
    branches:
      - release/*
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: version
        options:
        - patch
        - minor
        - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - name: Publish
      run: npm run deploy ${{ inputs.version }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
